### ISSUE TITLE
Add compact overlay theme

### ISSUE THREAD

**Issue by valterc** [valterc/ki2#141]
> Small request: the overlay takes a lot of room from the map. It's it possible to allow used to choose which info to show? for example, just the gear image and then remove everything below that?

**Comment by ttalonso** [comment]
I usually use the default map page. For me it would be very useful to have a few seconds the gear info. But since I have a single chainring on my bikes, only the rear Gear with a single number, type: 12, and that it was not intrusive with the map navigation would be very useful.

![20230214_172251](https://user-images.githubusercontent.com/30792615/226212129-b5ba0804-fcc3-453b-87d4-52d86d859c00.jpg)

**Comment by valterc** [comment]
Added a few more overlay themes and opacity setting, so now you could have something like this:
![Screenshot_20230410_102516](https://user-images.githubusercontent.com/1299179/230875729-aae03888-ac03-453c-a115-8ce597206f68.png)
