### ISSUE TITLE
Question for development

### ISSUE THREAD

**Issue by lockevod** [valterc/ki2#150]
Hello Valterc! Sorry for ask you another question. You know I'm trying to develope some kind of remote support. I'm very grateful for your code and for your last answer (about switch mapping, etc). 

I've been able to integrate ant remote (with a ant plus profile because a controller is a little diferent that a sensor or shift) and the app can change screens (inside course obviously) but I've a problem.

The problem is ... when I'm testing the app all works fine, but when I start a ride ( and connect my mobile and other ant devices) the response, sometimes, has a big delay (sometime 3s but sometimes 60 secons.. and it's like the actions are delaced , for example in a queue, and when the app has acces ... all actions are executed.. for exemple, if i push three times righ button, the app change three times the screen but with a delay of 60-90 seconds, for the first action)

I run one threat (for the ant listener in de kiservice) and I suppose there are other process that they have more priority than the app.. but this not happen with your app and hood buttons.

Could you help me ? I know your code (I've studied because I'm not an android developer . I've expertise wiht python, C++ , etc.. )
and if you can guide howto solve this in your code.

Thanks for your help

**Comment by valterc** [comment]
It can be many problems... ANT control is known to not be responsive (by design), that's why Di2 uses a custom profile/implementation. It might also be some implementation problem, try to log each step of your code and see what is taking the time.

As in, if you log and confirm that the information from ANT is received timely, then you know that the problem is in your stack (service, etc.), then debug/log each step to figure our what is causing the delay.
